Additional updates to ui & adding ability to choose download folder
linusg/spotifube pull request #14
Opened 2017-12-09 22:42 UTC by sdhutchins

Will address #6 and #7 

### Additions:
- Updated `resultMessage`

2017-12-09 22:43 UTC, sdhutchins commented
@djalmaaraujo @linusg I'm just going to leave this open as I make changes. I hope to finish tomorrow/Sunday afternoon. Took me a few days to get the hang of electron, but now, I feel better about it all.

2017-12-09 23:12 UTC, linusg requested changes

2017-12-09 23:12 UTC, linusg commented on package.json
> +        "copyright": "Copyright © 2017 [object Object]",
lol what's that? Copyright which belongs to a JS object?

2017-12-09 23:12 UTC, linusg commented on package.json
> +            "app": "C:\\Users\\Shaurita\\Documents\\GitRepo\\spotifube",
Please keep local dev paths out of any files commited.

2017-12-09 23:12 UTC, linusg commented on package.json
> +        "name": "Djalma Araújo"
Probably this is picky but I would rather add all three of us to the author field, as @djalmaaraujo is the _owner_ of the repo and by far not it's own _author_ :thinking:

2017-12-09 23:12 UTC, linusg commented on package.json
> +    },
In general, what's the point of indenting this file with four spaces? The tool it was generated by (`yarn init`) chose two and I would say that's fine.

2017-12-09 23:12 UTC, linusg commented on package.json
> +        "appId": "com.electron.spotifube",
Um, not sure if we would to it like this as `electron.com` does not belong to anyone of us... It may be even a non-existing domain, so reversed something like `com.spotifube.app`

2017-12-09 23:12 UTC, linusg commented on src/renderer/components/playlist-input/index.js
> +        this.setState({resultMessage: data,});
What's the point of the additional comma?

2017-12-09 23:12 UTC, linusg commented on src/renderer/components/playlist-input/index.js
> +            resultMessage: splitMessage[1] + " songs are available to download in this playlist.",
Better use formatting like

    const awesome = 'AWESOME';
    const foo = `This is ${awesome}!`;

2017-12-09 23:12 UTC, linusg commented on src/renderer/components/playlist-input/index.js
> +          let splitMessage = this.state.resultMessage.split(" ");
Should be `const` I think. I would suggest the constant use of single quotes in JS and double in HTML.

2017-12-09 23:12 UTC, linusg commented on src/renderer/scss/main.scss
> +    border-radius: 25px;
Radius is half the width/height, so `12.5px` which becomes `13px` after rounding up. Even though a bigger radius technically works it has no affect.

2017-12-09 23:12 UTC, linusg commented on src/renderer/scss/main.scss
> +      animation-delay: 0.6s;
Can't tell if this look better or worse, but let's see!

2017-12-09 23:12 UTC, linusg commented on src/renderer/scss/main.scss
> +   top: 20px;
Same as above, it's hard to purely imagine an animation from code only.

2017-12-09 23:12 UTC, linusg commented on README.md
> +A `GUI` for [@ritiek](https://github.com/ritiek)'s [`spotify-downloader`](https://github.com/ritiek/spotify-downloader/) project.
@ritiek
Are you fine with this kind of attribution, or should your name be left off and just the project's name, or...? This whole project is building up on work in large parts done by you so we should make sure you're happy with it. :smile:

2017-12-09 23:12 UTC, linusg commented on README.md
> +[`spotify-downloader`](https://github.com/ritiek/spotify-downloader/) is a command-line tool that matches Spotify tracks/playlists to youtube videos and downloads them as mp3/m4a, with id3, album art
Still picky, but if we write Spotify in a proper way (capital S) we have to write YouTube in a proper way too (capital Y and T).

2017-12-09 23:41 UTC, djalmaaraujo commented
I will review asap, please don't merge before. Need to take a deep look.

2017-12-10 04:20 UTC, sdhutchins commented
None of this is ready to merge or be reviewed. I opened the PR to let you guys know what I was working on so you guys could monitor it.

2017-12-10 04:21 UTC, sdhutchins commented
When I finish, I'll at you guys to review and suggest changes as I'm sure there will be many.

2017-12-10 04:21 UTC, sdhutchins commented on src/renderer/components/playlist-input/index.js
> +        this.setState({resultMessage: data,});
None. It's not cleaned up or ready to be merged.

2017-12-10 04:22 UTC, sdhutchins commented on package.json
> +        "appId": "com.electron.spotifube",
Also, not cleaned up or ready to be merged.

2017-12-10 04:22 UTC, sdhutchins commented on package.json
> +    },
I didnt indent this, electron toolkit automatically did.

2017-12-10 04:23 UTC, sdhutchins commented on package.json
> +        "copyright": "Copyright © 2017 [object Object]",
Against, electron toolkit generated all of this. Not ready to be merged.

2017-12-10 04:26 UTC, sdhutchins commented on README.md
> +[`spotify-downloader`](https://github.com/ritiek/spotify-downloader/) is a command-line tool that matches Spotify tracks/playlists to youtube videos and downloads them as mp3/m4a, with id3, album art
Yeah, just made a few edits to the existing Readme. The sentence was already here, I just moved it.

2017-12-10 04:28 UTC, sdhutchins commented
I have yet to commit what Im writing for 6 and 7 so reviewing this is premature which is why I let you guys know when I'd be done/ready for this to be reviewed.

2017-12-10 04:30 UTC, sdhutchins commented on package.json
> +            "app": "C:\\Users\\Shaurita\\Documents\\GitRepo\\spotifube",
It's not ready to be merged. I'm testing electron-toolkit for building the app and it created all of these paths.

2017-12-10 04:31 UTC, sdhutchins commented on src/renderer/components/playlist-input/index.js
> +            resultMessage: splitMessage[1] + " songs are available to download in this playlist.",
Thanks for this!

2017-12-10 04:32 UTC, sdhutchins commented on src/renderer/components/playlist-input/index.js
> +          let splitMessage = this.state.resultMessage.split(" ");
Just saw you had used this as well and was trying to keep with same style. I still have a lot to learn about js.

2017-12-10 04:32 UTC, sdhutchins commented on src/renderer/scss/main.scss
> +    border-radius: 25px;
It's splittting hairs form me. It's just bigger and I like it bigger, but not a priority

2017-12-10 05:46 UTC, ritiek commented on README.md
> +A `GUI` for [@ritiek](https://github.com/ritiek)'s [`spotify-downloader`](https://github.com/ritiek/spotify-downloader/) project.
Thanks! The link to the repository alone is enough to make me happy. :smile:
Do whatever seems okay to you guys, I won't mind at all.

2017-12-10 09:38 UTC, sdhutchins commented
> Anyone except me still working on anything? 🤔

The main reason I opened a PR was because this is covering more than 1 "issue", and I wanted to make sure that @linusg could track the actual progress of my commits because I understand that he wasn't sure if anyone was working on anything (and I have been for some days).

I've only added maybe 10% of what I need to add to address #6  and #7.  I've added very little code so at the moment - there is nothing relevant to review. I also have not cleaned any code.

Again, my goal is to have something by this afternoon (it's 3:33 am here), and when I have things ready (I'm very meticulous), I'll give you two a heads up.

I intend to follow along with @linusg's code style - I hate disjointed code bases so I'm not going to refactor his code at all.

In terms of the build stuff/package.json, none of that will be like what it is now - unless I get the build to work on my machine - I've just been trying out these node modules.

Additionally, I'll do a write up (as I do in other projects I belong to) in the main PR message to note what I changed/added/removed so it's easy to follow along.

2017-12-10 09:43 UTC, sdhutchins commented on package.json
> +        "name": "Djalma Araújo"
fwiw, i'd rather not be "named" in the project. Not really concerned with credit

2017-12-10 20:19 UTC, closed without merging

2017-12-11 14:29 UTC, djalmaaraujo commented on package.json
> +        "name": "Djalma Araújo"
@linusg I don't care about my name, if you want to move the repo to your username I can transfer and you put yourself as an author.

2017-12-11 14:32 UTC, djalmaaraujo commented on src/renderer/components/playlist-input/index.js
> +          let splitMessage = this.state.resultMessage.split(" ");
Should be const and we should always use single quotes.

2017-12-11 15:45 UTC, linusg commented on package.json
> +        "name": "Djalma Araújo"
@djalmaaraujo No, please don't get me wrong. I don't want to claim ownership either, but this whole thing is like a collaboration from the beginning. We all work and worked on this, so I would prefer to not have a single name here but either all of us or what about a generic 'The Spotifube developers'?

2017-12-11 17:25 UTC, sdhutchins commented on package.json
> +        "name": "Djalma Araújo"
@djalmaaraujo @linusg I will just leave it blank when I make my PR.